arch/arm/mm/init.c: fix CONFIG_SWAP=n build
In file included from arch/arm/mm/init.c:27:
arch/arm/include/asm/tlb.h: In function 'tlb_flush_mmu':
arch/arm/include/asm/tlb.h:104: error: implicit declaration of function 'release_pages'
arch/arm/include/asm/tlb.h: In function 'tlb_remove_page':
arch/arm/include/asm/tlb.h:168: error: implicit declaration of function 'page_cache_release'

free_pages_and_swap_cache() and free_page_and_swap_cache() are macros

which call release_pages() and page_cache_release().  The obvious fix is

to include pagemap.h in swap.h, where those macros are defined.  But that

breaks sparc for weird reasons.

So fix it within arch/arm/mm/init.c instead.

Fix originally by Andrew Morton for mm/pgtable-generic.c, commit f95ba941d1bee594d536cdcbf879a0865381b903